--- 
title: "The data-wrangling and omics course for R novices"
author: "Casper-Emil Tingskov Pedersen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "A tutorial on how to do data-wrangling and analysing omics data"
---

# Welcome to this course {#welcome}

We are happy that you want to join us in this venture to learn about data-wranling and analysing omics data.
A few things need to be checked before we start. First, you will need Rstudio, to install that go to
[RStudio](https://www.rstudio.com/products/rstudio/download/)

The best way to learn is to follow along with your own laptop, but all are welcome. We'll spend half the time with the lectures on the basic of R and data wrangling and half the time for you to try out wrangling yourself. You can also try out

The goal of this course is to equip you with the tools to take a virgin dataset and do the following:

1. Import data to R and understand the structure of your data
1. Look at it using summaries and descriptive statistics
1. Engineer features relevant for your research
1. Impute missing data
1. 

----


**Examples:**

We have been using bookdown for the Ocean Health Index:  [**ohi-science.org/data-science-training**](http://ohi-science.org/data-science-training) and Openscapes: [**openscapes.org/series**](https://openscapes.org/series).  
And R Markdown is much more than books and websites -- here's a [**one-minute video about R Markdown**](http://rmarkdown.rstudio.com/lesson-1.html) to get you excited. 

----

## Learn all about Bookdown

The best way to learn more about bookdown is from Yihui Xie himself. You can read his book [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/) or watch his webinar [introducing bookdown](https://www.rstudio.com/resources/webinars/introducing-bookdown/).

